//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTA_NEW_PORTAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountSearchMobile
    {
        public int AccID { get; set; }
        public Nullable<int> AccNo { get; set; }
        public string AccName { get; set; }
        public string AccMobile1 { get; set; }
        public string AccMobile2 { get; set; }
    }
}
