//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTA_NEW_PORTAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccID { get; set; }
        public Nullable<int> AccNo { get; set; }
        public string AccName { get; set; }
        public string AccName1 { get; set; }
        public string AccName2 { get; set; }
        public string AccName3 { get; set; }
        public string AccName4 { get; set; }
        public Nullable<byte> AccCategory { get; set; }
        public Nullable<byte> AccTitle { get; set; }
        public Nullable<byte> AccGender { get; set; }
        public Nullable<int> AccResp { get; set; }
        public string AccMemo { get; set; }
        public Nullable<byte> AccStatus { get; set; }
        public Nullable<byte> AccFile { get; set; }
        public byte[] AccPic { get; set; }
        public Nullable<int> UserCode { get; set; }
        public bool Cancelled { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<int> EnterUser { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public Nullable<System.TimeSpan> EnterTime { get; set; }
        public Nullable<int> ModUser { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<System.TimeSpan> ModTime { get; set; }
    }
}
