//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTA_NEW_PORTAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataAccInfoType
    {
        public byte InfoTypeID { get; set; }
        public string InfoTypeName { get; set; }
        public string InfoTypeCategory { get; set; }
    }
}
