//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTA_NEW_PORTAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysMenuRun
    {
        public int MenuID { get; set; }
        public Nullable<int> MenuLevel { get; set; }
        public string MenuHeader { get; set; }
        public string MenuSort { get; set; }
        public string MenuName { get; set; }
        public byte[] MenuPic { get; set; }
        public Nullable<int> ns { get; set; }
    }
}
